### ISSUE TITLE
08 -- Surf & Paddle, RWD Edition -- John Alexander

### ISSUE THREAD

**Issue by johnalxndr** [TheIronYard--Orlando/FEE--2015--SPRING#100]
* [x] **Yak Shaving**
* [x] Create a new issue with tasks and estimates
* [x] Create a new branch based on `master` named `08--surf+paddle+rwd`
* [x] Download, add, and commit the design specs -- [`full.png`](full.png) and [`small.png`](small.png) -- to `specs/`
* [x] Push and open a Pull Request to `master` (maybe try using `hub pull-request`?)
* [x]  **BONUS:** Name your PR something _other_ than the commit message?
* [x] **Skitch!**
* [x] Checkpoint: Committed `full.png` and `small.png`
* [x] Checkpoint: Annotated full-size header
* [x] Checkpoint: Annotated small-size header
* [x] Checkpoint: Annotated full-size article
* [x] Checkpoint: Annotated small-size article
* [x] Checkpoint: Annotated full-size footer
* [x] Checkpoint: Annotated small-size footer
* [x] Checkpoint: Annotated full-size sidebar
* [x] Checkpoint: Annotated small-size sidebar
* [ ] **Surf & Paddle RWD**
* [x] Checkpoint: Clean slate
* [x] Checkpoint: HTML5 Boilerplate
* [x] Checkpoint: Adding assets for logo
* [x] Checkpoint: Linked fonts for icons and copy
* [x] Checkpoint: Small-size header complete!
* [x] Checkpoint: Small-size footer complete!
* [x] Checkpoint: Small-size columns complete!
* [x] Checkpoint: Small-size article complete!
* [x] Checkpoint: Small-size sidebar complete!
* [x] Checkpoint: Small-size layout complete!
* [x] Checkpoint: Small-size header complete!
* [ ] Checkpoint: Full-size footer complete!
* [ ] Checkpoint: Full-size columns complete!
* [ ] Checkpoint: Full-size article complete!
* [ ] Checkpoint: Full-size sidebar complete!
* [ ] Checkpoint: Full-size layout complete!
* [ ] Checkpoint: Medium-size header complete!
* [ ] Checkpoint: Medium-size footer complete!
* [ ] Checkpoint: Medium-size columns complete!
  * Checkpoint: Medium-size article complete!
  * Checkpoint: Medium-size sidebar complete!
  * Checkpoint: Medium-size layout complete!
* [ ] **Build a Blog**
  * [x] Checkpoint: Repository exists!
  * [x] Checkpoint: Hello, blog!
  * [x] Checkpoint: HTML5 Boilerplate again?
  * [x] Checkpoint: Basic MF'g HTML
  * [x] Checkpoint: Basic 2-column layout
  * [x] Checkpoint: Header fully styled!
  * [ ] Checkpoint: Footer fully styled!
  * [ ] Checkpoint: Look, ma, I'm a blogger!
  * [ ] Mission Complete!

**Comment by johnalxndr** [comment]
https://github.com/johnalxndr/TIY-Assignments/pull/8

**Comment by johnalxndr** [comment]
BUGS
* [ ] *bottom boxes wont stack side by side for medium screen size
* [ ] *
* [ ] *

**Comment by johnalxndr** [comment]
* [ ] *

**Comment by johnalxndr** [comment]
http://johnalxndr.github.io/

**Comment by johnalxndr** [comment]
BUGS/GITHUB-BLOG
* [ ] Footer wont line up properly 
* [ ] profile pic move to center for mobile media query
* [ ] Icons underneath each post

**Comment by LoganArnett** [comment]
Make sure that you commit often to really keep track of your progress and to continue to get the 2 :+1: on those PR's
