### ISSUE TITLE
08--surf+paddle+rwd -- Carolina Powers

### ISSUE THREAD

**Issue by carolinapowers** [TheIronYard--Orlando/FEE--2015--SPRING#101]
### Tasks

* [x] **Yak Shaving** (L)
  * Create a new issue with tasks and estimates
  * Create a new branch based on `master` named `08--surf+paddle+rwd`
  * Download, add, and commit the design specs -- [`full.png`](full.png) and [`small.png`](small.png) -- to `specs/`
  * Push and open a Pull Request to `master` (maybe try using `hub pull-request`?)
  * **BONUS:** Name your PR something _other_ than the commit message?
* [x] **Skitch!** (M)
  * Checkpoint: Committed `full.png` and `small.png`
  * Checkpoint: Annotated full-size header
  * Checkpoint: Annotated small-size header
  * Checkpoint: Annotated full-size article
  * Checkpoint: Annotated small-size article
  * Checkpoint: Annotated full-size footer
  * Checkpoint: Annotated small-size footer
  * Checkpoint: Annotated full-size sidebar
  * Checkpoint: Annotated small-size sidebar
* [x] **Surf & Paddle RWD** (XL)
  * Checkpoint: Clean slate
  * Checkpoint: HTML5 Boilerplate
  * Checkpoint: Adding assets for logo
  * Checkpoint: Linked fonts for icons and copy
  * Checkpoint: Small-size header complete!
  * Checkpoint: Small-size footer complete!
  * Checkpoint: Small-size columns complete!
  * Checkpoint: Small-size article complete!
  * Checkpoint: Small-size sidebar complete!
  * Checkpoint: Small-size layout complete!
  * Checkpoint: Small-size header complete!
  * Checkpoint: Full-size footer complete!
  * Checkpoint: Full-size columns complete!
  * Checkpoint: Full-size article complete!
  * Checkpoint: Full-size sidebar complete!
  * Checkpoint: Full-size layout complete!
  * Checkpoint: Medium-size header complete!
  * Checkpoint: Medium-size footer complete!
  * Checkpoint: Medium-size columns complete!
  * Checkpoint: Medium-size article complete!
  * Checkpoint: Medium-size sidebar complete!
  * Checkpoint: Medium-size layout complete!
* [x] **Build a Blog** (XL)
  * Checkpoint: Repository exists!
  * Checkpoint: Hello, blog!
  * Checkpoint: HTML5 Boilerplate again?
  * Checkpoint: Basic MF'g HTML
  * Checkpoint: Basic 2-column layout
  * Checkpoint: Header fully styled!
  * Checkpoint: Footer fully styled!
  * Checkpoint: Look, ma, I'm a blogger!
  * Mission Complete!

**Comment by carolinapowers** [comment]
https://github.com/carolinapowers/TIY-Assignments/pull/8

**Comment by carolinapowers** [comment]
https://github.com/carolinapowers/TIY-Assignments/blob/08--surf%2Bpaddle%2Brwd/pub/index.html

**Comment by carolinapowers** [comment]
Checklist of bugs in my S&P:

[ ]  Footer text and image floating properly.
[ ] Make the width of the article buttons the same width.
[ ] Refine the hover state of buttons and pictures in the bottom.
[ ] Make the side bar a little more liquid.

**Comment by carolinapowers** [comment]
http://carolinapowers.github.io

**Comment by carolinapowers** [comment]
Checklist of bugs in my GP:

* [ ] Footer text and image floating properly when resizing the window.

**Comment by LoganArnett** [comment]
Awesome job Carolina :white_check_mark:
