### ISSUE TITLE
08 -- Surf&Paddle, RWD Edition -- Garrett Lee Graham Anderson

### ISSUE THREAD

**Issue by GarrettGraham** [TheIronYard--Orlando/FEE--2015--SPRING#107]
* [x] **Yak Shaving**(L)
  * [x] Create a new issue with tasks and estimates
  * [x] Create a new branch based on `master` named `08--surf+paddle+rwd`
  * [x] Download, add, and commit the design specs -- [`full.png`](full.png) and [`small.png`](small.png) -- to `specs/`
  * [??? ] Push and open a Pull Request to `master` (maybe try using `hub pull-request`?)???
  * [x] **BONUS:** Name your PR something _other_ than the commit message?
* [x] **Skitch!**(M)
  * [x] Checkpoint: Committed `full.png` and `small.png`
  * [x] Checkpoint: Annotated full-size header
  * [x] Checkpoint: Annotated small-size header
  * [x] Checkpoint: Annotated full-size article
  * [x] Checkpoint: Annotated small-size article
  * [x] Checkpoint: Annotated full-size footer
  * [x] Checkpoint: Annotated small-size footer
  * [x] Checkpoint: Annotated full-size sidebar
  * [x] Checkpoint: Annotated small-size sidebar
* [x] **Surf & Paddle RWD** (XL)
  * [x] Checkpoint: Clean slate
  * [x] Checkpoint: HTML5 Boilerplate
  * [x] Checkpoint: Adding assets for logo
  * [x] Checkpoint: Linked fonts for icons and copy
  * [ ] Checkpoint: Small-size header complete!
  * [x] Checkpoint: Small-size footer complete!
  * [ ] Checkpoint: Small-size columns complete! ??there are columns in a mobile view??
  * [x] Checkpoint: Small-size article complete!
  * [ ] Checkpoint: Small-size sidebar complete!  ??sidebars in mobile??
  * [x] Checkpoint: Small-size layout complete!
  * [x] Checkpoint: Small-size header complete!
  * [ ] Checkpoint: Full-size footer complete!
  * [ ] Checkpoint: Full-size columns complete!
  * [ ] Checkpoint: Full-size article complete!
  * [ ] Checkpoint: Full-size sidebar complete!
  * [ ] Checkpoint: Full-size layout complete!
  * [ ] Checkpoint: Medium-size header complete!
  * [ ] Checkpoint: Medium-size footer complete!
  * [ ] Checkpoint: Medium-size columns complete!
  * [ ] Checkpoint: Medium-size article complete!
  * [ ] Checkpoint: Medium-size sidebar complete!
  * [ ] Checkpoint: Medium-size layout complete!
* [ ] **Build a Blog**(XL)
  * [x] Checkpoint: Repository exists!
  * [x] Checkpoint: Hello, blog!
  * [x] Checkpoint: HTML5 Boilerplate again?
  * [x] Checkpoint: Basic MF'g HTML
  * [ ] Checkpoint: Basic 2-column layout
  * [ ] Checkpoint: Header fully styled!
  * [ ] Checkpoint: Footer fully styled!
  * [ ] Checkpoint: Look, ma, I'm a blogger!
  * [ ] Mission Complete!

**Comment by GarrettGraham** [comment]
https://github.com/GarrettGraham/TIY-Assignments/pull/7

**Comment by GarrettGraham** [comment]
https://github.com/GarrettGraham/GarrettGraham.github.io

**Comment by LoganArnett** [comment]
Looking for the checklist of the known issues, other than that great job :white_check_mark:
