### ISSUE TITLE
08--surf+paddle+rwd -- Maddie Fees

### ISSUE THREAD

**Issue by mfees** [TheIronYard--Orlando/FEE--2015--SPRING#109]
* [x] **Yak Shaving** (S)
  * [x] Create a new issue with tasks and estimates
  * [x] Create a new branch based on `master` named `08--surf+paddle+rwd`
  * [x] Download, add, and commit the design specs -- [`full.png`](full.png) and [`small.png`](small.png) -- to `specs/`
  * [x] Push and open a Pull Request to `master` (maybe try using `hub pull-request`?)
  * [x] **BONUS:** Name your PR something _other_ than the commit message?
* [x] **Skitch!** (M)
  * [x] Checkpoint: Committed `full.png` and `small.png`
  * [x] Checkpoint: Annotated full-size header
  * [x] Checkpoint: Annotated small-size header
  * [x] Checkpoint: Annotated full-size article
  * [x] Checkpoint: Annotated small-size article
  * [x] Checkpoint: Annotated full-size footer
  * [x] Checkpoint: Annotated small-size footer
  * [x] Checkpoint: Annotated full-size sidebar
  * [x] Checkpoint: Annotated small-size sidebar
* [ ] **Surf & Paddle RWD** (XL)
  * [x] Checkpoint: Clean slate
  * [x] Checkpoint: HTML5 Boilerplate
  * [x] Checkpoint: Adding assets for logo
  * [x] Checkpoint: Linked fonts for icons and copy
  * [ ] Checkpoint: Small-size header complete!
  * [ ] Checkpoint: Small-size footer complete!
  * [ ] Checkpoint: Small-size columns complete!
  * [ ] Checkpoint: Small-size article complete!
  * [ ] Checkpoint: Small-size sidebar complete!
  * [ ] Checkpoint: Small-size layout complete!
  * [ ] Checkpoint: Small-size header complete!
  * [ ] Checkpoint: Full-size footer complete!
  * [ ] Checkpoint: Full-size columns complete!
  * [ ] Checkpoint: Full-size article complete!
  * [ ] Checkpoint: Full-size sidebar complete!
  * [ ] Checkpoint: Full-size layout complete!
  * [ ] Checkpoint: Medium-size header complete!
  * [ ] Checkpoint: Medium-size footer complete!
  * [ ] Checkpoint: Medium-size columns complete!
  * [ ] Checkpoint: Medium-size article complete!
  * [ ] Checkpoint: Medium-size sidebar complete!
  * [ ] Checkpoint: Medium-size layout complete!
* [x] **Build a Blog** (L)
  * [x] Checkpoint: Repository exists!
  * [x] Checkpoint: Hello, blog!
  * [x] Checkpoint: HTML5 Boilerplate again?
  * [x] Checkpoint: Basic MF'g HTML
  * [x] Checkpoint: Basic 2-column layout
  * [x] Checkpoint: Header fully styled!
  * [x] Checkpoint: Footer fully styled!
  * [x] Checkpoint: Look, ma, I'm a blogger!
  * [x] Mission Complete!

**Comment by mfees** [comment]
## Deliverables

* [ ] A new _WIP Issue_ in the class repo with tasks and estimates
* [ ] A new branch in `TIY-Assignments` named `08--surf+paddle+rwd` with:
  * [ ] a commit that deletes your previous assignment
  * [ ] a commit that imports HTML5 Boilerplate (use Yeoman, if you know how)
  * [ ] multiple commits to `pub/index.html` and `css/main.css` no more than 1 hour apart
  * [ ] a _pixel-perfect_ rendering of the full and small designs
  * [ ] a medium size layout and appropriate breakpoint
  * [ ] icons courtesy of Font Awesome, Glyphicons, or Octicons
  * [ ] placeholder text and images (linked, not downloaded)
* [ ] A PR from your feature branch to `master` with:
  * [ ] a link to your _WIP Issue_
  * [ ] a link to your `index.html` on [HTML Preview](http://htmlpreview.github.io)
  * [ ] feedback and 2x :+1:'s from your peers
* [ ] A new repository called `USERNAME.github.io` with:
  * [ ] HTML5 Boilerplate
  * [ ] multiple commits to `index.html` and `css/main.css`
  * [ ] a pixel-perfect implementation of [Longform](https://www.pixelunion.net/themes/tumblr/longform/)
  * [ ] a single blog post
* [ ] Comments on your _WIP Issue_ with:
  * [ ] a link to your PR
  * [ ] a checklist of bugs in your S&P implementation
  * [ ] a link to your GH Pages site
  * [ ] a checklist of bugs in your GH Pages implementation

**Comment by mfees** [comment]
https://github.com/mfees/TIY-Assignments/pull/12

**Comment by mfees** [comment]
## Things I broke:

* [ ] Number one
* [ ] Number two

**Comment by mfees** [comment]
http://mfees.github.io/

**Comment by LoganArnett** [comment]
Looks good Maddie :cat:

**Comment by al-the-x** [comment]
Don't sweat the blog so much, Maddie. We'll get to it this week.
