### ISSUE TITLE
09 -- Hello Javascript! -- John Alexander

### ISSUE THREAD

**Issue by johnalxndr** [TheIronYard--Orlando/FEE--2015--SPRING#118]
* **Yak Shaving**--M
  * [x] Create a new _WIP Issue_ with tasks _and estimates!_
  * [x] Create a new branch called `09--hello-javascript`
  * [x] Create and commit a new file in `docs/` called `JS.md`
  * [x] Push the branch to Github and open a PR
  * [x] Name the PR _descriptively_...
* **Reading JavaScript**--XL
  * [x] Checkpoint: Created and committed `JS.md`!
  * [x] Checkpoint: First Literal Documented!
  * [x] Checkpoint: All Literals Documented!
  * [x] Checkpoint: To Infinity and beyond!
  * [x] Checkpoint: First Operator
  * [x] Checkpoint: Five Operators
  * [ ] Checkpoint: All Ten Operators!
  * [ ] Mission Complete!
* **What's In A Grid?**--L
  * [x] Checkpoint: Reset to Boilerplate!
  * [x] Checkpoint: Basic HTML structure!
  * [x] Checkpoint: Look at all the colors...
  * [x] Checkpoint: Looks great in any viewport!
  * [x] Mission Complete!

**Comment by johnalxndr** [comment]
https://github.com/johnalxndr/TIY-Assignments/pull/11

**Comment by LoganArnett** [comment]
Looks good John :white_check_mark:
