### ISSUE TITLE
09 -- Hello JavaScript! -- Maddie Fees

### ISSUE THREAD

**Issue by mfees** [TheIronYard--Orlando/FEE--2015--SPRING#120]
* **Yak Shaving** (S)
  * [x] Create a new _WIP Issue_ with tasks _and estimates!_
  * [x] Create a new branch called `09--hello-javascript`
  * [x] Create and commit a new file in `docs/` called `JS.md`
  * [x] Push the branch to Github and open a PR
  * [x] Name the PR _descriptively_...
* **Reading JavaScript** (L)
  * [x] Checkpoint: Created and committed `JS.md`!
  * [x] Checkpoint: First Literal Documented!
  * [x] Checkpoint: All Literals Documented!
  * [x] Checkpoint: To Infinity and beyond!
  * [x] Checkpoint: First Operator
  * [x] Checkpoint: Five Operators
  * [x] Checkpoint: All Ten Operators!
  * [x] Mission Complete!
* **What's In A Grid?** (L)
  * [x] Checkpoint: Reset to Boilerplate!
  * [x] Checkpoint: Basic HTML structure!
  * [x] Checkpoint: Look at all the colors...
  * [x] Checkpoint: Looks great in any viewport!
  * [x] Mission Complete!

**Comment by mfees** [comment]
## Deliverables

* [ ] A _WIP Issue_ named `09 -- Hello JavaScript!` with tasks and estimates
* [ ] A branch in `TIY-Assignments` named `feature/09--hello-javascript` with:
  * [ ] a _new_ file in `docs/` called `JS.md` with documentation matching **Requirements**
  * [ ] a commit resetting `pub/` to base HTML5 Boilerplate
  * [ ] an implementation in `pub/index.html` of:
    * [ ] a 8x8 grid of perfect squares
    * [ ] alternating dark and light colors in each square
    * [ ] distinct border between cells
    * [ ] rows labeled "8" to "1"
    * [ ] columns labeled "a" to "h"
    * [ ] cell "d8" as dark
* [ ] A PR in `TIY-Assignments` from `feature/09--hello-javascript` to `master` with:
  * [ ] a link to your _WIP Issue_
  * [ ] 2x peer review
* [ ] Links in your _WIP Issue_ to:
  * [ ] your PR in `TIY-Assignments`

**Comment by mfees** [comment]
https://github.com/mfees/TIY-Assignments/pull/13

**Comment by LoganArnett** [comment]
Looks good Maddie :white_check_mark:
