### ISSUE TITLE
09 -- Hello JavaScript! -- Evan Klemen

### ISSUE THREAD

**Issue by eklemen** [TheIronYard--Orlando/FEE--2015--SPRING#122]
* M **Yak Shaving**
  * [x] Create a new _WIP Issue_ with tasks _and estimates!_
  * [x] Create a new branch called `09--hello-javascript`
  * [x] Create and commit a new file in `docs/` called `JS.md`
  * [x] Push the branch to Github and open a PR
  * [x] Name the PR _descriptively_...
* L **Reading JavaScript**
  * [x] Checkpoint: Created and committed `JS.md`!
  * [x] Checkpoint: First Literal Documented!
  * [x] Checkpoint: All Literals Documented!
  * [x] Checkpoint: To Infinity and beyond!
  * [x] Checkpoint: First Operator
  * [x] Checkpoint: Five Operators
  * [x] Checkpoint: All Ten Operators!
  * [x] Mission Complete!
* XtraMedium **What's In A Grid?**
  * [x] Checkpoint: Reset to Boilerplate!
  * [x] Checkpoint: Basic HTML structure!
  * [x] Checkpoint: Look at all the colors...
  * [x] Checkpoint: Looks great in any viewport!
  * [x] Mission Complete!

**Comment by eklemen** [comment]
https://github.com/eklemen/TIY-Assignments/pull/9

**Comment by LoganArnett** [comment]
Looks good just need to drop the link to this issue into the comments on that PR then you're good to go :vertical_traffic_light:

**Comment by eklemen** [comment]
Oops thought i did!
