### ISSUE TITLE
02 -- Learning Layout -- Maddie Fees

### ISSUE THREAD

**Issue by mfees** [TheIronYard--Orlando/FEE--2015--SPRING#31]
* [x] **(S) Yak Shaving** -- There's always one more...
    * [X] Create a new _WIP Issue_ in the class repo titled `02 -- Learning Layout -- YOUR NAME`
    * [x] Add these checkboxes as the description!
    * [x] [Login to Cloud 9 IDE](http://c9.io/login) using your Github account
    * [x] Clone your `TIY-Assignments` repository into a new Workspace and open it
    * [x] Using the Terminal, create a new branch from `master` called `feature/02--learning-layout` and switch to it (hint: `checkout`)
    * [x] Create a new file in `docs/` called `CSS.md` and commit it.
    * [x] Create a new file in `pub/` called `index.html` and commit it.
    * [x] Push your branch into the `origin` remote
    * [x] _Immediately_ open a Pull Request (PR) _from_ `feature/02--learning-layout` _into_ `master`
* [x] **(S) Draft Outline** -- 4 main sections
    * [x] Introduction
    * [x] 3 main points
    * [x] Conclusion
    * [x] Add link to _WIP Issue_!
* [ ] **(S) Read [Learn Layout](http://learnlayout.com)**
* [x] **(M) Reading CSS** -- Document the CSS properties presented in "Learn Layout"
    * [x] Checkpoint: First CSS property committed and pushed!
    * [x] Checkpoint: 5 CSS properties committed and pushed!
    * [x] Checkpoint: 10 CSS properties committed and pushed!
    * [x] Mission Complete: You know layout!
* [x] **(M) Reading HTML** -- Part deaux: _10 more tags!_
    * [x] Checkpoint: Here's number 11!
    * [x] Checkpoint: 15 done, committed, and pushed!
    * [x] Mission Complete: 10 + 10 is 20 HTML tags! Ha ha ha ha!
* [ ] **(M) The Iron Blog** -- It doesn't have to be complicated...
    * [x] Page header with placeholder image, logo
    * [ ] Page footer with logo and links
    * [x] Side column with headings and links
    * [x] Main column:
        * [x] 3 articles with headings and placeholder text
        * [x] 3 placeholder images
        * **bonus** -- article footer + icons!

**Comment by mfees** [comment]
### Deliverables

* [ ] A new _WIP Issue_ in the class repository titled `02 -- Learning Layout -- YOUR NAME` with:
    * [ ] checkboxes for the **Tasks** outlined under **Requirements**
    * [ ] estimates for the top-level checkboxes
* [ ] A draft outline of a 3-point essay in your _Growth and Fixed Mindset_ wiki page.
* [ ] A branch in your `TIY-Assignments` repository _besed on `master`_ called `feature/02--learning-layout` with:
    * [ ] 10 additional HTML tags in `docs/HTML.md`
    * [ ] A new file in `docs/` called `CSS.md` documenting the _un-prefixed_ CSS properties presented in "Learn Layout" in the format provided under **Requirements**
    * [ ] A new file in `pub/` called `index.html` that contains:
        * [ ] HTML and CSS to replicate [The Longform Tumblr theme](https://www.pixelunion.net/themes/tumblr/longform/) in use by [The Iron Yard -- Orlando blog](http://orlando.theironyard.com)
        * [ ] placeholder text and images of your choosing
        * [ ] minimally: page header and footer, logo, and both columns
* [ ] A Pull Request (PR) in your `TIY-Assignments` repo:
    * [ ] _from_ branch `feature/02--learning-layout` (head)
    * [ ] _into_ branch `master` (base)
    * [ ] with a description that links to your _WIP Issue_ in the class repo
    * [ ] and 2 :thumbsup: comments from peers who have reviewed your work
* [ ] Comments on your _WIP Issue_ with:
    * [ ] a link to your wiki page
    * [ ] a link to your PR

**Comment by mfees** [comment]
https://github.com/mfees/TIY-Assignments/pull/4

**Comment by mfees** [comment]
https://github.com/mfees/TIY-Assignments/wiki

**Comment by mfees** [comment]
https://github.com/mfees/TIY-Assignments/pull/5

**Comment by LoganArnett** [comment]
Looks good just looking for the the content of index.html file for the blog and you have a small formatting issue to check out in your last few [HTML elements](https://github.com/mfees/TIY-Assignments/blob/feature/02--learning-layout/docs/html.md).
