### ISSUE TITLE
02 -- Learning Layout -- Jon Rutishauser

### ISSUE THREAD

**Issue by jrutishauser** [TheIronYard--Orlando/FEE--2015--SPRING#33]
* [x] **Yak Shaving** -- There's always one more... --> S
    * [X] Create a new _WIP Issue_ in the class repo titled `02 -- Learning Layout -- YOUR NAME`
    * [x] Add these checkboxes as the description!
    * [x] [Login to Cloud 9 IDE](http://c9.io/login) using your Github account
    * [x] Clone your `TIY-Assignments` repository into a new Workspace and open it
    * [x] Using the Terminal, create a new branch from `master` called `feature/02--learning-layout` and switch to it (hint: `checkout`)
    * [x] Create a new file in `docs/` called `CSS.md` and commit it.
    * [x] Create a new file in `pub/` called `index.html` and commit it.
    * [x] Push your branch into the `origin` remote
    * [x] _Immediately_ open a Pull Request (PR) _from_ `feature/02--learning-layout` _into_ `master`
* [x] **Draft Outline** -- 4 main sections -->S
    * [x] Introduction
    * [x] 3 main points
    * [x] Conclusion
    * [x] Add link to _WIP Issue_!
* [x] **Read [Learn Layout](http://learnlayout.com)** -->M
* [x] **Reading CSS** -- Document the CSS properties presented in "Learn Layout" -->M
    * [x] Checkpoint: First CSS property committed and pushed!
    * [x] Checkpoint: 5 CSS properties committed and pushed!
    * [x] Checkpoint: 10 CSS properties committed and pushed!
    * [x] Mission Complete: You know layout!
* [x] **Reading HTML** -- Part deaux: _10 more tags!_ -->S
    * [x] Checkpoint: Here's number 11!
    * [x] Checkpoint: 15 done, committed, and pushed!
    * [x] Mission Complete: 10 + 10 is 20 HTML tags! Ha ha ha ha!
* [x] **The Iron Blog** -- It doesn't have to be complicated... -->L
    * [x] Page header with placeholder image, logo
    * [x] Page footer with logo and links
    * [x] Side column with headings and links
    * [x] Main column:
        * [x] 3 articles with headings and placeholder text
        * [x] 3 placeholder images
        * **bonus** -- article footer + icons!

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by jrutishauser** [comment]
https://github.com/jrutishauser/TIY-Assignments/pull/3

**Comment by LoganArnett** [comment]
Looks good Jon

**Comment by al-the-x** [comment]
For your essay, in paras III and IV, talk more about your experience with the two mindsets as a way of explaining what they are. This will reinforce the concepts better in your own head _and_ present a better story.

**Comment by al-the-x** [comment]
Great work to date! Keep it up!
