### ISSUE TITLE
30 -- Angularize Me -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#340]
## Requirements
- [x]  _WIP Issue:_ `30 -- Angularize Me`
  - [x] link to any PRs you open in `TIY-Catalog`
  - [x] link to your PR in `TIY-Assignments`
- [ ] _WIP Branch:_
  - [x] `TIY-Catalog:feature/gulp-dev-tasks`
  - [x] `TIY-Assignments:feature/30--angularize-me`
- [ ] _Deliverables:_
  - [x] `TIY-Catalog:angular/`
    - [x] `README.md` -- new User Stories
    - [ ] `bower.json` -- adding Angular JS, Gulp JS
    - [ ] `gulpfile.js` -- adding `gulp` tasks
      - [x] `gulp sass` -- build `src/scss/*.scss` to `src/css/*.css` via `node-sass`
      - [ ] `gulp sass:watch` -- run `gulp sass` on file change
      - [ ] `gulp serve:dev` -- serve `angular/src/` via `browser-sync`
      - [ ] `gulp serve:dev:watch` -- serve and watch
    - [ ] `apis/etsy/` -- new API data / docs / ops
    - [x] `src/` -- progress on UI widgets
      - [x] `menu.html`
      - [ ] `products.html`
      - [ ] `product.html`
      - [ ] `scss/`
        - [ ] `menu.scss`
        - [ ] `products.scss`
        - [ ] `product.scss`
  - [x] `TIY-Assignments:pub/`
    - [x] Codeschool levels 2-3

**Comment by jrutishauser** [comment]
thanks for giving me something to copy

**Comment by jaredstevick** [comment]
Link to PR:
https://github.com/TheIronYard--Orlando/TIY-Catalog/pull/11
