### ISSUE TITLE
Ready Read (for now) -- John Alexander Taylor Foster

### ISSUE THREAD

**Issue by TaylorFoster90** [TheIronYard--Orlando/FEE--2015--SPRING#355]
@taylorfoster90
@johnalxndr

**Comment by TaylorFoster90** [comment]
## MVP:
- User can log in ( _TBD:_ either through facebook or pocket) to view bookmarked articles.
- User can browse bookmarked items via mobile-first/responsive UI.
- User can can filter bookmarked articles/blog posts by calculated read time.
- User can add new articles to bookmark. 
- User can read chosen article via different formats (color/font-size/theme)

## Tech-Stack:
- Angular JS
- RestAngular to access the API(s)
- AngularFire / Firebase
- Bootstrap
- Gulp
- Sass
- Lodash

**Comment by adamkarb** [comment]
Closing this issue due to irrelevance
