### ISSUE TITLE
02 -- Learning Layout -- Evan Klemen

### ISSUE THREAD

**Issue by eklemen** [TheIronYard--Orlando/FEE--2015--SPRING#36]
* [x] M **Yak Shaving** -- There's always one more...
    * [X] Create a new _WIP Issue_ in the class repo titled `02 -- Learning Layout -- YOUR NAME`
    * [x] Add these checkboxes as the description!
    * [x] [Login to Cloud 9 IDE](http://c9.io/login) using your Github account
    * [x] Clone your `TIY-Assignments` repository into a new Workspace and open it
    * [x] Using the Terminal, create a new branch from `master` called `feature/02--learning-layout` and switch to it (hint: `checkout`)
    * [x] Create a new file in `docs/` called `CSS.md` and commit it.
    * [x] Create a new file in `pub/` called `index.html` and commit it.
    * [x] Push your branch into the `origin` remote
    * [x] _Immediately_ open a Pull Request (PR) _from_ `feature/02--learning-layout` _into_ `master`
* [x] S **Draft Outline** -- 4 main sections
    * [x] Introduction
    * [x] 3 main points
    * [x] Conclusion
    * [x] Add link to _WIP Issue_!
* [x] M **Read [Learn Layout](http://learnlayout.com)**
* [x] M **Reading CSS** -- Document the CSS properties presented in "Learn Layout"
    * [x] Checkpoint: First CSS property committed and pushed!
    * [x] Checkpoint: 5 CSS properties committed and pushed!
    * [x] Checkpoint: 10 CSS properties committed and pushed!
    * [x] Mission Complete: You know layout!
* [x] M **Reading HTML** -- Part deaux: _10 more tags!_
    * [x] Checkpoint: Here's number 11!
    * [x] Checkpoint: 15 done, committed, and pushed!
    * [x] Mission Complete: 10 + 10 is 20 HTML tags! Ha ha ha ha!
* [x] L **The Iron Blog** -- It doesn't have to be complicated...
    * [x] Page header with placeholder image, logo
    * [x] Page footer with logo and links
    * [x] Side column with headings and links
    * [x] Main column:
        * [x] 3 articles with headings and placeholder text
        * [x] 3 placeholder images
        * **bonus** -- article footer + icons!

**Comment by eklemen** [comment]
https://github.com/eklemen/TIY-Assignments/pull/3

**Comment by eklemen** [comment]
https://github.com/eklemen/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by LoganArnett** [comment]
Looks good Evan, just have one syntax fix in your introduction of your wiki and looking for 1 more :+1: on your PR
