### ISSUE TITLE
02 -- Learning Layout -- Garrett Lee Graham Anderson

### ISSUE THREAD

**Issue by GarrettGraham** [TheIronYard--Orlando/FEE--2015--SPRING#40]
* [x] **Yak Shaving** -- There's always one more... (M)
    * [X] Create a new _WIP Issue_ in the class repo titled `02 -- Learning Layout -- YOUR NAME`
    * [x] Add these checkboxes as the description!
    * [x] [Login to Cloud 9 IDE](http://c9.io/login) using your Github account
    * [x] Clone your `TIY-Assignments` repository into a new Workspace and open it
    * [x] Using the Terminal, create a new branch from `master` called `feature/02--learning-layout` and switch to it (hint: `checkout`)
    * [x] Create a new file in `docs/` called `CSS.md` and commit it.
    * [x] Create a new file in `pub/` called `index.html` and commit it.
    * [x] Push your branch into the `origin` remote
    * [x] _Immediately_ open a Pull Request (PR) _from_ `feature/02--learning-layout` _into_ `master`
* [x] **Draft Outline** -- 4 main sections (M)
    * [x] Introduction
    * [x] 3 main points
    * [x] Conclusion
    * [x] Add link to _WIP Issue_!
* [ ] **Read [Learn Layout](http://learnlayout.com)** (M)
* [x] **Reading CSS** -- Document the CSS properties presented in "Learn Layout" (L)
    * [x] Checkpoint: First CSS property committed and pushed!
    * [x] Checkpoint: 5 CSS properties committed and pushed!
    * [ ] Checkpoint: 10 CSS properties committed and pushed!
    * [ ] Mission Complete: You know layout!
* [x] **Reading HTML** -- Part deux: _10 more tags!_ (L)
    * [x] Checkpoint: Here's number 11!
    * [x] Checkpoint: 15 done, committed, and pushed!
    * [ ] Mission Complete: 10 + 10 is 20 HTML tags! Ha ha ha ha!
* [ ] **The Iron Blog** -- It doesn't have to be complicated...(L)
    * [ ] Page header with placeholder image, logo
    * [ ] Page footer with logo and links
    * [ ] Side column with headings and links
    * [ ] Main column:
        * [ ] 3 articles with headings and placeholder text
        * [ ] 3 placeholder images
        * **bonus** -- article footer + icons!

**Comment by GarrettGraham** [comment]
https://github.com/GarrettGraham/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by LoganArnett** [comment]
Looks good Garrett, just looking for a few more HTML and CSS elements and the link to that open PR for this feature branch with 2 :+1:
