### ISSUE TITLE
03 -- Be Like Water -- Garrett Lee Graham Anderson

### ISSUE THREAD

**Issue by GarrettGraham** [TheIronYard--Orlando/FEE--2015--SPRING#43]
* **Yak Shaving**(S)
    * [X] Open a new Issue in the class repo and...
    * [X] Add these checkboxes to your Issue.
    * [x] [Login to Cloud 9](http://c9.io/login) and open your `TIY-Assignments` Workspace
    * [x] Create and switch to a new branch named `feature/03--like-water` from `master`. _Ensure you have `master` checked out and up-to-date before you start!_
    * [x] Add a commit that clears or deletes your `pub/index.html` file
    * [x] Push your work into Github
    * [x] _Immediately_ open a PR _from_ `feature/03--like-water` _into_ `master`
* **Rough Draft** of your _Growth and Fixed Mindset_ essay on your wiki page.(M)
* **Reading HTML + Attributes!**(L)
    * [x] Checkpoint: First attribute documented and committed!
    * [ ] Checkpoint: Global attributes documented and committed!
    * [x] Checkpoint: First HTML tag _fully_ documented and committed!
    * [ ] Checkpoint: 5 HTML tags _fully_ documented and committed!
    * [ ] Checkpoint: 10 HTML tags _fully_ documented and committed!
    * [ ] Checkpoint: First push with attributes!
    * [ ] Checkpoint: Halfway to finish and pushed!
    * [ ] Mission Complete: All tags documented, committed, and pushed!
* **Skitch This Website** -- Because you can...(L)
    * [x] Use `brew cask` to find and install [Skitch](http://evernote.com/skitch)
    * [x] Using Skitch Capture several screenshots of [The Iron Yard -- Orlando](http://orlando.theironyard.com) site that demonstrate key pieces of the design
    * [x] Export them and upload to Cloud 9 in a new folder called `specs/`
    * [x] Add and commit them into your project history
    * [ ] Mark up the screenshots to denote:
        * the tag names and bounding boxes of semantic block-level elements
        * essential CSS properties and values like `margin` and `padding` or `font-family`
        * image URLs or special character codes necessary for typographic elements
        * anything else that will help you execute the design!
    * [ ] Export the marked-up images and upload to Cloud 9, overwriting the originals in `specs/`
    * [ ] Add and commit the updated images
    * Repeat as necessary for additional design direction.
* **The Iron Blog** -- Be like water, my friend... or :beer:(XL)
    * [ ] Checkpoint: Clean slate! :zero:
    * [ ] Checkpoint: Yay Boilerplate! :one:
    * [ ] Checkpoint: Basic page structure (HTML only)! :two:
    * [ ] Checkpoint: First line of CSS committed and pushed! :star:
    * [ ] Checkpoint: Placeholders anyone? :baby_bottle:
    * [ ] Checkpoint: Who's got a header image and logo? :raised_hand:
    * [ ] Checkpoint: How many columns you got? :dancers:
    * [ ] Checkpoint: Where's that footer? :point_down:
    * [ ] Checkpoint: Matching fonts. :muscle:
    * [ ] Checkpoint: Check out those round logos... :sunglasses:
    * [ ] Checkpoint: Much fluid. So amaze. :ocean:
    * [ ] Checkpoint: Icons are totally dessert. :ice_cream:
    * [ ] Mission Complete: :triumph:

**Comment by LoganArnett** [comment]
Hey Garret, looking for the links to the PR and the Rough Draft of the Wiki, after that just keep working on those elements and experimenting with the Blog layout

**Comment by al-the-x** [comment]
Let's talk this week about getting you unstuck. Your commit messages are great, and I love that you're just _trying_ stuff on Assignment 04 rather than giving up or cheating yourself. You have the least prior exposure to these concepts of the class and you're probably the strongest visual learner of the bunch. We need to capitalize on that to catch you up!
