### ISSUE TITLE
03 -- Be Like Water...- Maddie Fees

### ISSUE THREAD

**Issue by mfees** [TheIronYard--Orlando/FEE--2015--SPRING#44]
* **(S) Yak Shaving**
    * [X] Open a new Issue in the class repo and...
    * [X] Add these checkboxes to your Issue.
    * [x] [Login to Cloud 9](http://c9.io/login) and open your `TIY-Assignments` Workspace
    * [x] Create and switch to a new branch named `feature/03--like-water` from `master`. _Ensure you have `master` checked out and up-to-date before you start!_
    * [x] Add a commit that clears or deletes your `pub/index.html` file
    * [x] Push your work into Github
    * [x] _Immediately_ open a PR _from_ `feature/03--like-water` _into_ `master`
* [X] **(M) Rough Draft** of your _Growth and Fixed Mindset_ essay on your wiki page.
* [ ] **(M) Reading HTML + Attributes!**
    * [ ] Checkpoint: First attribute documented and committed!
    * [ ] Checkpoint: Global attributes documented and committed!
    * [ ] Checkpoint: First HTML tag _fully_ documented and committed!
    * [ ] Checkpoint: 5 HTML tags _fully_ documented and committed!
    * [ ] Checkpoint: 10 HTML tags _fully_ documented and committed!
    * [ ] Checkpoint: First push with attributes!
    * [ ] Checkpoint: Halfway to finish and pushed!
    * [ ] Mission Complete: All tags documented, committed, and pushed!
* **(S) Skitch This Website** -- Because you can...
    * [x] Use `brew cask` to find and install [Skitch](http://evernote.com/skitch)
    * [x] Using Skitch Capture several screenshots of [The Iron Yard -- Orlando](http://orlando.theironyard.com) site that demonstrate key pieces of the design
    * [x] Export them and upload to Cloud 9 in a new folder called `specs/`
    * [x] Add and commit them into your project history
    * [x] Mark up the screenshots to denote:
        * the tag names and bounding boxes of semantic block-level elements
        * essential CSS properties and values like `margin` and `padding` or `font-family`
        * image URLs or special character codes necessary for typographic elements
        * anything else that will help you execute the design!
    * [x] Export the marked-up images and upload to Cloud 9, overwriting the originals in `specs/`
    * [x] Add and commit the updated images
    * Repeat as necessary for additional design direction.
* **(L) The Iron Blog** -- Be like water, my friend... or :beer:
    * [x] Checkpoint: Clean slate! :zero:
    * [x] Checkpoint: Yay Boilerplate! :one:
    * [x] Checkpoint: Basic page structure (HTML only)! :two:
    * [x] Checkpoint: First line of CSS committed and pushed! :star:
    * [x] Checkpoint: Placeholders anyone? :baby_bottle:
    * [x] Checkpoint: Who's got a header image and logo? :raised_hand:
    * [x] Checkpoint: How many columns you got? :dancers:
    * [ ] Checkpoint: Where's that footer? :point_down:
    * [x] Checkpoint: Matching fonts. :muscle:
    * [x] Checkpoint: Check out those round logos... :sunglasses:
    * [x] Checkpoint: Much fluid. So amaze. :ocean:
    * [ ] Checkpoint: Icons are totally dessert. :ice_cream:
    * [ ] Mission Complete: :triumph:

**Comment by mfees** [comment]
## Deliverables

* [ ] A new _WIP Issue_ in the class repository titled `03 -- Be Like Water -- YOUR NAME` with:
    * [ ] checkboxes for the *Tasks* under *Requirements*
    * [ ] estimates for the top-level tasks
* [ ] A [Rough Draft](http://www.studygs.net/writing/roughdrafts.htm) for your _Growth and Fixed Mindset_ essay in your wiki page
* [ ] A branch in your `TIY-Assignments` repository _based on `master`_ called `feature/03--like-water` with:
    * [ ] documentation of the HTML attributes for the tags you've already documented added to `docs/HTML.md` per the format provided in **Requirements**
    * [ ] marked up design specifications (screenshots) in `specs/`
    * [ ] at least one commit clearing or deleting your `pub/index.html` file
    * [ ] multiple commits adding HTML and CSS into `pub/index.html` to provide a liquid-style layout that:
        * [ ] remains consistent at all screen sizes
        * [ ] becomes fixed-width at an appropriate "large" size
        * [ ] remains proportional while resized down
        * [ ] becomes fixed-width at an appropriate "small" size
* [ ] A Pull Request (PR) _from_ your feature branch _into_ `master` with:
    * [ ] a link back to your _WIP Issue_
    * [ ] 2x :thumbsup: from peers
    * [ ] **Don't check off on _any_ PR until you _see_ the code rendered and confirm it meets the requirements!**
* [ ] Comments on your _WIP Issue_ with:
    * [ ] a link to your wiki page
    * [ ] a link to your PR

**Comment by mfees** [comment]
https://github.com/mfees/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by mfees** [comment]
https://github.com/mfees/TIY-Assignments/pull/7

**Comment by LoganArnett** [comment]
The Blog is looking good Maddie, just finish up those HTML elements and you're good to go

**Comment by al-the-x** [comment]
Like how you're also checkboxing the **Deliverables** section in another comment. Very smart.

**Comment by al-the-x** [comment]
Great work on your essay, Maddie. Keep in mind how those messages from your past will creep back up on you as you try to learn something hard: "We expected better..." is dangerous territory. Can't wait to see your next draft, and be sure to keep your brainstorming, outline, and pervious drafts while you develop your thoughts.
