### ISSUE TITLE
03 -- Be Like Water -- Evan Klemen

### ISSUE THREAD

**Issue by eklemen** [TheIronYard--Orlando/FEE--2015--SPRING#53]
* ** M Yak Shaving**
    * [X] Open a new Issue in the class repo and...
    * [X] Add these checkboxes to your Issue.
    * [x] [Login to Cloud 9](http://c9.io/login) and open your `TIY-Assignments` Workspace
    * [x] Create and switch to a new branch named `feature/03--like-water` from `master`. _Ensure you have `master` checked out and up-to-date before you start!_
    * [x] Add a commit that clears or deletes your `pub/index.html` file
    * [x] Push your work into Github
    * [x] _Immediately_ open a PR _from_ `feature/03--like-water` _into_ `master`
* ** M Rough Draft** of your _Growth and Fixed Mindset_ essay on your wiki page.
* ** L Reading HTML + Attributes!**
    * [x] Checkpoint: First attribute documented and committed!
    * [x] Checkpoint: Global attributes documented and committed!
    * [x] Checkpoint: First HTML tag _fully_ documented and committed!
    * [x] Checkpoint: 5 HTML tags _fully_ documented and committed!
    * [x] Checkpoint: 10 HTML tags _fully_ documented and committed!
    * [x] Checkpoint: First push with attributes!
    * [x] Checkpoint: Halfway to finish and pushed!
    * [x] Mission Complete: All tags documented, committed, and pushed!
* ** M Skitch This Website** -- Because you can...
    * [x] Use `brew cask` to find and install [Skitch](http://evernote.com/skitch)
    * [x] Using Skitch Capture several screenshots of [The Iron Yard -- Orlando](http://orlando.theironyard.com) site that demonstrate key pieces of the design
    * [x] Export them and upload to Cloud 9 in a new folder called `specs/`
    * [x] Add and commit them into your project history
    * [x] Mark up the screenshots to denote:
        * the tag names and bounding boxes of semantic block-level elements
        * essential CSS properties and values like `margin` and `padding` or `font-family`
        * image URLs or special character codes necessary for typographic elements
        * anything else that will help you execute the design!
    * [x] Export the marked-up images and upload to Cloud 9, overwriting the originals in `specs/`
    * [x] Add and commit the updated images
    * Repeat as necessary for additional design direction.
* XL **The Iron Blog** -- Be like water, my friend... or :beer:
    * [x] Checkpoint: Clean slate! :zero:
    * [x] Checkpoint: Yay Boilerplate! :one:
    * [x] Checkpoint: Basic page structure (HTML only)! :two:
    * [x] Checkpoint: First line of CSS committed and pushed! :star:
    * [x] Checkpoint: Placeholders anyone? :baby_bottle:
    * [x] Checkpoint: Who's got a header image and logo? :raised_hand:
    * [x] Checkpoint: How many columns you got? :dancers:
    * [x] Checkpoint: Where's that footer? :point_down:
    * [x] Checkpoint: Matching fonts. :muscle:
    * [x] Checkpoint: Check out those round logos... :sunglasses:
    * [x] Checkpoint: Much fluid. So amaze. :ocean:
    * [x] Checkpoint: Icons are totally dessert. :ice_cream:
    * [x] Mission Complete: :triumph:

**Comment by eklemen** [comment]
https://github.com/eklemen/TIY-Assignments/pull/4

**Comment by eklemen** [comment]
https://github.com/eklemen/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by LoganArnett** [comment]
Looks good Evan, just need those :+1: on the PR and to keep checking on that fluid layout

**Comment by al-the-x** [comment]
So the header image didn't load for me when I checked it out, but the rest looked pretty good. I'm starting to notice a rash of `class="page-column-main"` going around the group that was hunkered down around the center tables. Is that something you figured out together?
