### ISSUE TITLE
04 -- Surf & Paddle -- Maddie Fees

### ISSUE THREAD

**Issue by mfees** [TheIronYard--Orlando/FEE--2015--SPRING#56]
* **Yak Shaving** (S)
    * [X] Create a new _WIP Issue_ called `04 -- Surf & Paddle -- YOUR NAME` with these tasks as the description
    * [x] Add estimates to top-level tasks
    * [x] Break down any _L_ or _XL_ tasks into smaller tasks and estimate; repeat
    * [x] Create a branch on Cloud 9 called `feature/04--surf+paddle`
    * [x] Add at least one commit and push to Github
    * [x] Open a PR linked to your _WIP Issue_
* **To the Final Drafts!** (M)
    * [x] Checkpoint: First draft in progress!
    * [x] Checkpoint: First draft complete!
    * [x] Checkpoint: First round of feedback!
    * [x] Checkpoint: First revisions!
    * [x] Checkpoint: Second draft complete!
    * [ ] Checkpoint: More feedback, more revisions!
    * [ ] Mission Complete!
* **Skitch that Paddle** (M)
    * [x] Checkpoint: Loaded the design spec into Skitch! 
    * [x] Checkpoint: Skitched the page header, exported, uploaded and committed! 
    * [x] Checkpoint: Skitched the page footer, exported, uploaded and committed! 
    * [x] Checkpoint: Skitched the main article, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the sidebar, exported, uploaded and committed!
    * [x] Mission Complete!
* **Now Surf!** (L)
    * [x] Checkpoint: HTML5 Boilerplate committed! (S)
    * [x] Checkpoint: Basic HTML structure committed! (S)
    * [x] Checkpoint: Basic layout CSS committed! (S)
    * [x] Checkpoint: Pixel perfect page header committed! (M)
    * [x] Checkpoint: Pixel perfect page footer committed! (M)
    * [x] Checkpoint: Pixel perfect column layout committed! (M)
    * [x] Checkpoint: Pixel perfect layout and typography committed! (M)
    * [x] Checkpoint: Links with hover states committed! (M)
    * [x] Mission complete!

**Comment by mfees** [comment]
## Deliverables

* [ ] A new _WIP Issue_ named `04 -- Surf & Paddle -- YOUR NAME` with tasks and estimates.
* [ ] _At least two (2) drafts_ of your essay:
    * [ ] Keep each draft in the same wiki page but *do not overwrite*
    * [ ] Provide an explicit link to _each_ draft in your _WIP Issue_
    * [ ] *hint:* try hovering over a heading
* [ ] A branch in your `TIY-Assignments` repository _based on `master`_ named `feature/04--surf+paddle` with:
    * [ ] Revisions to your HTML and CSS documentation that:
        * [ ] incorporate feedback or recommendations from previous assignments
        * [ ] complete the previous assignments in full
    * [ ] Marked up design specifications in `specs/` based on `specs/full.png`:
        * [ ] use **Skitch** to chop out pieces of the design
        * [ ] markup and export files
        * [ ] upload to Cloud 9 and commit
    * [ ] Multiple commits to with good commit messages (not [these](http://whatthecommit.com))
    * [ ] Modifications to `pub/index.html` and `pub/css/main.css` (from HTML5 Boilerplate)
* [ ] A PR from your feature branch into `master` with:
    * [ ] a link back to your _WIP Issue_
    * [ ] 2x :thumbsup: from peers
    * [ ] feedback from peers as commentary
* [ ] Comments on your _WIP Issue_ with:
    * [ ] a link to your wiki page
    * [ ] a link to your PR
    * [ ] feedback on your essay from peers

**Comment by mfees** [comment]
https://github.com/mfees/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by mfees** [comment]
https://github.com/mfees/TIY-Assignments/pull/9

**Comment by eklemen** [comment]
Read over the essay, I would say for the main paragraphs just explain what carol dweck defines "fixed" or "growth" mindset as, to give reference to.  :+1:

**Comment by mfees** [comment]
https://github.com/mfees/TIY-Assignments/wiki/Growth-and-Fixed-Mindset#rough-draft

**Comment by mfees** [comment]
https://github.com/mfees/TIY-Assignments/wiki/Growth-and-Fixed-Mindset#draft

**Comment by LoganArnett** [comment]
The Cat and Kitten Co looks great just make sure to look at those previous assignments and make sure you're not missing any major concepts from those
