### ISSUE TITLE
04 -- Surf & Paddle -- Taylor Foster

### ISSUE THREAD

**Issue by TaylorFoster90** [TheIronYard--Orlando/FEE--2015--SPRING#62]
* **Yak Shaving** (M)
    * [X] Create a new _WIP Issue_ called `04 -- Surf & Paddle -- YOUR NAME` with these tasks as the description
    * [x] Add estimates to top-level tasks
    * [x] Break down any _L_ or _XL_ tasks into smaller tasks and estimate; repeat
    * [x] Create a branch on Cloud 9 called `feature/04--surf+paddle`
    * [x] Add at least one commit and push to Github
    * [x] Open a PR linked to your _WIP Issue_
* **To the Final Drafts!** (M)
    * [x] Checkpoint: First draft in progress!
    * [x] Checkpoint: First draft complete!
    * [x] Checkpoint: First round of feedback!
    * [x] Checkpoint: First revisions!
    * [x] Checkpoint: Second draft complete!
    * [x] Checkpoint: More feedback, more revisions!
    * [x] Mission Complete!
* **Skitch that Paddle** (M)
    * [x] Checkpoint: Loaded the design spec into Skitch!
    * [x] Checkpoint: Skitched the page header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the page footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the main article, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the sidebar, exported, uploaded and committed!
    * [x] Mission Complete!
* **Now Surf!** (XL)
    * [x] Checkpoint: HTML5 Boilerplate committed!
    * [x] Checkpoint: Basic HTML structure committed!
    * [x] Checkpoint: Basic layout CSS committed!
    * [x] Checkpoint: Pixel perfect page header committed!
    * [x] Checkpoint: Pixel perfect page footer committed!
    * [x] Checkpoint: Pixel perfect column layout committed!
    * [x] Checkpoint: Pixel perfect layout and typography committed!
    * [x] Checkpoint: Links with hover states committed!
    * [x] Mission complete!

**Comment by TaylorFoster90** [comment]
https://github.com/TaylorFoster90/TIY-Assignments/pull/4

**Comment by TaylorFoster90** [comment]
https://github.com/TaylorFoster90/TIY-Assignments/wiki/Growth-and-Fixed-Mindset#growth-mindset-essay

**Comment by TaylorFoster90** [comment]
https://github.com/TaylorFoster90/TIY-Assignments/wiki/Growth-and-Fixed-Mindset#draft-2

**Comment by LoganArnett** [comment]
The site looks awesome man, great job on the drafts but make sure to ask your peers for their input on them for possible revisions. Also, try to remember to add the link back to the WIP issue on the PR as a comment.

**Comment by al-the-x** [comment]
Watchc the formatting on your checkboxes, bro. It's a little wonky. Copy and paste from the **raw** text of the assignment to alleviate against whoopsies.

**Comment by al-the-x** [comment]
Good job tearing through all of this, Taylor, but like Logan said, you need to solicit the input of your peers. Don't just drop a link on Github and expect them to remember or allocate time to review your work and leave feedback. Actively pursue the criticism of others. Your essay needs some polish. There are typos and grammatical errors and you never really explain the mindsets. It's also too short for a traditional 3-point thesis. Get some feedback and give it another draft.

If there's one thing that I've seen in you this week, it's your super-positive attitude and dilligence to get the work done. You've been an inspiration. Conversely, I've also seen you go Han Solo more times than I can count. While you've always been quick to help someone if they ask, be sure to actively pursue opportunities to help others. When you finish a task, don't just commit and push and check a box: make sure that your team has gotten as far as you have. You'll learn more by teaching than you will by building. Keep it up!
