### ISSUE TITLE
04 -- Surf & Paddle -- Garrett Lee Graham Anderson

### ISSUE THREAD

**Issue by GarrettGraham** [TheIronYard--Orlando/FEE--2015--SPRING#63]
* **Yak Shaving** (S)
    * [X] Create a new _WIP Issue_ called `04 -- Surf & Paddle -- YOUR NAME` with these tasks as the description
    * [x] Add estimates to top-level tasks
    * [x] Break down any _L_ or _XL_ tasks into smaller tasks and estimate; repeat
    * [x] Create a branch on Cloud 9 called `feature/04--surf+paddle`
    * [x] Add at least one commit and push to Github
    * [x] Open a PR linked to your _WIP Issue_
* **To the Final Drafts!** (M)
    * [ ] Checkpoint: First draft in progress!
    * [ ] Checkpoint: First draft complete!
    * [ ] Checkpoint: First round of feedback!
    * [ ] Checkpoint: First revisions!
    * [ ] Checkpoint: Second draft complete!
    * [ ] Checkpoint: More feedback, more revisions!
    * [ ] Mission Complete!
* **Skitch that Paddle** (L)
    * [x] Checkpoint: Loaded the design spec into Skitch!
    * [x] Checkpoint: Skitched the page header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the page footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the main article, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the sidebar, exported, uploaded and committed!
    * [x] Mission Complete!
* **Now Surf!** (XL)
    * [x] Checkpoint: HTML5 Boilerplate committed!
    * [ ] Checkpoint: Basic HTML structure committed!
    * [ ] Checkpoint: Basic layout CSS committed!
    * [ ] Checkpoint: Pixel perfect page header committed!
    * [ ] Checkpoint: Pixel perfect page footer committed!
    * [ ] Checkpoint: Pixel perfect column layout committed!
    * [ ] Checkpoint: Pixel perfect layout and typography committed!
    * [ ] Checkpoint: Links with hover states committed!
    * [ ] Mission complete!

**Comment by LoganArnett** [comment]
Great job on the skitches of the site, you are locating the correct concepts as you think through the process and break it down visually. It is just going to take a little time to keep working through the trial and error of the CSS properties with the HTML layout. 

Make sure to get those :+1: for that PR and to link to the PR and to your drafts of the wiki once completed
