### ISSUE TITLE
04 --Surf & Paddle -- John Alexander

### ISSUE THREAD

**Issue by johnalxndr** [TheIronYard--Orlando/FEE--2015--SPRING#65]
* **Yak Shaving**
    * [X] Create a new _WIP Issue_ called `04 -- Surf & Paddle -- YOUR NAME` with these tasks as the description
    * [x] Add estimates to top-level tasks
    * [x] Break down any _L_ or _XL_ tasks into smaller tasks and estimate; repeat
    * [x] Create a branch on Cloud 9 called `feature/04--surf+paddle`
    * [x] Add at least one commit and push to Github
    * [x] Open a PR linked to your _WIP Issue_
* **To the Final Drafts!**--M
    * [x] Checkpoint: First draft in progress!
    * [x] Checkpoint: First draft complete!
    * [ ] Checkpoint: First round of feedback!
    * [ ] Checkpoint: First revisions!
    * [ ] Checkpoint: Second draft complete!
    * [ ] Checkpoint: More feedback, more revisions!
    * [ ] Mission Complete!
* **Skitch that Paddle**--S
    * [x] Checkpoint: Loaded the design spec into Skitch!
    * [x] Checkpoint: Skitched the page header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the page footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the main article, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the sidebar, exported, uploaded and committed!
    * [x] Mission Complete!
* **Now Surf!**--XXL
    * [x] Checkpoint: HTML5 Boilerplate committed!
    * [x] Checkpoint: Basic HTML structure committed!
    * [x] Checkpoint: Basic layout CSS committed!
    * [ ] Checkpoint: Pixel perfect page header committed!
    * [ ] Checkpoint: Pixel perfect page footer committed!
    * [ ] Checkpoint: Pixel perfect column layout committed!
    * [ ] Checkpoint: Pixel perfect layout and typography committed!
    * [ ] Checkpoint: Links with hover states committed!
    * [ ] Mission complete!

**Comment by johnalxndr** [comment]
* **Yak Shaving**
    * [X] Create a new _WIP Issue_ called `04 -- Surf & Paddle -- YOUR NAME` with these tasks as the description
    * [ ] Add estimates to top-level tasks
    * [ ] Break down any _L_ or _XL_ tasks into smaller tasks and estimate; repeat
    * [ ] Create a branch on Cloud 9 called `feature/04--surf+paddle`
    * [ ] Add at least one commit and push to Github
    * [ ] Open a PR linked to your _WIP Issue_
* **To the Final Drafts!**
    * [ ] Checkpoint: First draft in progress!
    * [ ] Checkpoint: First draft complete!
    * [ ] Checkpoint: First round of feedback!
    * [ ] Checkpoint: First revisions!
    * [ ] Checkpoint: Second draft complete!
    * [ ] Checkpoint: More feedback, more revisions!
    * [ ] Mission Complete!
* **Skitch that Paddle**
    * [ ] Checkpoint: Loaded the design spec into Skitch!
    * [ ] Checkpoint: Skitched the page header, exported, uploaded and committed!
    * [ ] Checkpoint: Skitched the page footer, exported, uploaded and committed!
    * [ ] Checkpoint: Skitched the main article, exported, uploaded and committed!
    * [ ] Checkpoint: Skitched the article header, exported, uploaded and committed!
    * [ ] Checkpoint: Skitched the article footer, exported, uploaded and committed!
    * [ ] Checkpoint: Skitched the sidebar, exported, uploaded and committed!
    * [ ] Mission Complete!
* **Now Surf!**
    * [ ] Checkpoint: HTML5 Boilerplate committed!
    * [ ] Checkpoint: Basic HTML structure committed!
    * [ ] Checkpoint: Basic layout CSS committed!
    * [ ] Checkpoint: Pixel perfect page header committed!
    * [ ] Checkpoint: Pixel perfect page footer committed!
    * [ ] Checkpoint: Pixel perfect column layout committed!
    * [ ] Checkpoint: Pixel perfect layout and typography committed!
    * [ ] Checkpoint: Links with hover states committed!
    * [ ] Mission complete!

**Comment by johnalxndr** [comment]
https://github.com/johnalxndr/TIY-Assignments/wiki/Growth-and-Fixed-Mindsets

**Comment by johnalxndr** [comment]
def not done but happy with my progress 
https://github.com/johnalxndr/TIY-Assignments/pull/4

**Comment by LoganArnett** [comment]
The site looks great man, good use or the outlines to really see how things are moving and relating to each other. One thing with the organization of your projects is you should try to label the files more specifically so you know what they contain. For example, Surf+Paddle as a file name with that initializr file located inside of that. That will help to keep your repo clean as you go through the class and into your career.

Other than that just reach out to your peers for help on your essay and revision suggestions and you're good to go.

**Comment by jaredstevick** [comment]
:+1:  better late than never lol
