### ISSUE TITLE
04 -- Surf & Paddle -- Evan Klemen

### ISSUE THREAD

**Issue by eklemen** [TheIronYard--Orlando/FEE--2015--SPRING#66]
* ** M Yak Shaving**
    * [X] Create a new _WIP Issue_ called `04 -- Surf & Paddle -- YOUR NAME` with these tasks as the description
    * [X] Add estimates to top-level tasks
    * [x] Break down any _L_ or _XL_ tasks into smaller tasks and estimate; repeat
    * [x] Create a branch on Cloud 9 called `feature/04--surf+paddle`
    * [x] Add at least one commit and push to Github
    * [x] Open a PR linked to your _WIP Issue_
* ** L To the Final Drafts!**
    * [x] Checkpoint: First draft in progress!
    * [x] Checkpoint: First draft complete!
    * [x] Checkpoint: First round of feedback!
    * [x] Checkpoint: First revisions!
    * [x] Checkpoint: Second draft complete!
    * [ ] Checkpoint: More feedback, more revisions!
    * [ ] Mission Complete!
* L **Skitch that Paddle**
    * [x] Checkpoint: Loaded the design spec into Skitch!
    * [x] Checkpoint: Skitched the page header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the page footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the main article, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article header, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the article footer, exported, uploaded and committed!
    * [x] Checkpoint: Skitched the sidebar, exported, uploaded and committed!
    * [x] Mission Complete!
* XL **Now Surf!**
    * [x] Checkpoint: HTML5 Boilerplate committed!
    * [x] Checkpoint: Basic HTML structure committed!
       * [x] Header
       * [x] 2 column layout
       * [ ] footer
         * [x] 4 images
    * [x] Checkpoint: Basic layout CSS committed!
    * [x] Checkpoint: Pixel perfect page header committed!
    * [x] Checkpoint: Pixel perfect page footer committed!
    * [x] Checkpoint: Pixel perfect column layout committed!
    * [x] Checkpoint: Pixel perfect layout and typography committed!
    * [x] Checkpoint: Links with hover states committed!
    * [x] Mission complete!

**Comment by eklemen** [comment]
https://github.com/eklemen/TIY-Assignments/pull/5

**Comment by eklemen** [comment]
https://github.com/eklemen/TIY-Assignments/wiki/Growth-and-Fixed-Mindset#first-draft

**Comment by al-the-x** [comment]
@TheIronYard--Orlando/fee-2015-spring Does this work? It's supposed to...

**Comment by al-the-x** [comment]
Okay @TheIronYard--Orlando/fee-2015-spring let's see if I fixed it...!

**Comment by mfees** [comment]
Dang @eklemen,

Awesome essay, blew mine out of the water lol. The only suggestion I have is to maybe rework the last paragraph a bit. You start out with Carol Dweck and end with her but in the middle you define what the mindsets are and your experiences with them but then kind of add more information about Carol again. Try just to highlight your points in the conclusion.

Really great job 
:+1:

(wanted to put this in the right spot)

**Comment by jrutishauser** [comment]
:+1:  page looks great.

**Comment by LoganArnett** [comment]
Great work on the Surf and Paddle Page and the Essay. Just looking for the 2 :+1: on that PR then you're good to go
