### ISSUE TITLE
05 -- Even More Layout -- Maddie Fees

### ISSUE THREAD

**Issue by mfees** [TheIronYard--Orlando/FEE--2015--SPRING#71]
* [x] **Yak Shaving** -- The Holy Checklist (S)
    * [x] Open a new _WIP Issue_ with **Tasks**
    * [x] Estimate top-level tasks
    * [x] Update your Cloud 9 workspace: `git pull`
    * [x] Create a new branch from `master`
    * [x] Commit the deletion of your previous assignment
    * [x] Push to Github and open a PR
* [x] **Design Specifications** -- Use **Skitch** to create design specs and store them in `specs/` (M)
* [x] [**Vertical Timeline**](http://theironyard-orlando.github.io/FEE--2015--SPRING/) (XL)
  * [x] Checkpoint: New project clearinghouse :0:
  * [x] Checkpoint: HTML5 Boilerplate :1:
  * [x] Checkpoint: Semantic HTML structure :seedling:
  * [x] Checkpoint: Basic CSS layout :seedling::seedling:
  * [x] Checkpoint: Icons are for decoration :blossom:
  * [x] Checkpoint: Time is floating :hourglass:
  * [x] Checkpoint: Walk the line :guitar:
  * [x] Mission Complete! :checkered_flag:
* **BONUS** -- Skitch the _Responsive Breakpoints_

**Comment by mfees** [comment]
## Deliverables

* [ ] A _WIP Issue_ called `05 -- Even More Layout -- YOUR NAME` with:
    * [ ] **Tasks** from the **Requirements** section
    * [ ] estimates on top-level tasks
* [ ] A branch in your `TIY-Assignments` repo named `feature/05--more-layout` with:
    * [ ] commits that:
        * [ ] delete your `pub/` directory or its contents
        * [ ] delete your `specs/` directory or its contents
        * [ ] adds the file `_config.yml` as provided in **Requirements**
    * [ ] multiple commits no more than 1 hour apart with _good_ commit messages
    * [ ] annotated design specs in `specs/`
    * [ ] HTML and CSS in `pub/index.html` and `pub/css/main.css`
* [ ] A branch in your `TIY_Assignments` repo named `gh-pages` based on `feature/05--more-layout` with:
    * [ ] the most functional version of your code!
* [ ] A PR in your `TIY-Assignments` repo with:
    * [ ] a link to your _WIP Issue_
    * [ ] feedback from peers
    * [ ] 2x :+1:'s from peers
* [ ] Comments in your _WIP Issue_ with:
    * [ ] a link to your PR
    * [ ] a link to your `gh-pages` site: `http://USERNAME.github.io/TIY-Assignments`
    * [ ] a checklist of bugs in your deployed version
* **Pro Tip:** Try deploying `gh-pages` _early_!

**Comment by mfees** [comment]
https://github.com/mfees/TIY-Assignments/pull/10

**Comment by mfees** [comment]
### Things to fix:

* Getting timestamps to correct position
* Adding line
* Positioning line
* Adding circled icons
* Positioning icons
* Making sure it is all liquid
* Changing paragraph headlines and body copy

**Comment by LoganArnett** [comment]
You have a great frame for the timeline, just needs a little more tinkering for that sidebar and icons. Ask your peers for those :+1: on the PR and you're good to go
