### ISSUE TITLE
05 -- Even More Layout -- John Alexander

### ISSUE THREAD

**Issue by johnalxndr** [TheIronYard--Orlando/FEE--2015--SPRING#73]
* [x] **Yak Shaving** -- The Holy Checklist--M
    * [x] ** Open a new _WIP Issue_ with **Tasks**
    * [x] **Estimate top-level tasks
    * [x] **Update your Cloud 9 workspace: `git pull`
    * [x] ** Create a new branch from `master`
    * [x] **Commit the deletion of your previous assignment
    * [x] **Push to Github and open a PR
* [x] **Design Specifications** -- Use **Skitch** to create design specs and store them in `specs/`
* [x] [**Vertical Timeline**](http://theironyard-orlando.github.io/FEE--2015--SPRING/)--XXL
  * [x] Checkpoint: New project clearinghouse :0:--S
  * [x] Checkpoint: HTML5 Boilerplate :1:--S
  * [x] Checkpoint: Semantic HTML structure :seedling:--L
  * [x] Checkpoint: Basic CSS layout :seedling::seedling:--XL
  * [x] Checkpoint: Icons are for decoration :blossom:--M
  * [x] Checkpoint: Time is floating :hourglass:--L
  * [x] Checkpoint: Walk the line :guitar:--L
  * [x] Checkpoint: First deployment! :squirrel:--L
  * [ ] Mission Complete! :checkered_flag:
* **BONUS** -- Skitch the _Responsive Breakpoints_

**Comment by johnalxndr** [comment]
https://github.com/johnalxndr/TIY-Assignments/pull/5

**Comment by johnalxndr** [comment]
BUGS
* [ ] **lining up icons on horizontal line
* [ ] **font problems
* [ ] **time stamp issue
* [ ] **top left marker tag in each box
* [ ] **FLUID!

**Comment by LoganArnett** [comment]
Great job on the timeline man, just gotta keep fiddling with the monster that is CSS to lock in that layout
