### ISSUE TITLE
05 -- Even More Layout -- Garrett Lee Graham Anderson

### ISSUE THREAD

**Issue by GarrettGraham** [TheIronYard--Orlando/FEE--2015--SPRING#77]
* [x] **Yak Shaving** -- The Holy Checklist -- S
    * [x] Open a new _WIP Issue_ with **Tasks**
    * [x] Estimate top-level tasks
    * [x] Update your Cloud 9 workspace: `git pull`
    * [x] Create a new branch from `master`
    * [x] Commit the deletion of your previous assignment
    * [x] Push to Github and open a PR
* [ ] **Design Specifications** -- Use **Skitch** to create design specs and store them in `specs/` -- M
* [x] [**Vertical Timeline**](http://theironyard-orlando.github.io/FEE--2015--SPRING/) -- XL
  * [x] Checkpoint: New project clearinghouse :zero: 
  * [x] Checkpoint: HTML5 Boilerplate :one:
  * [ ] Checkpoint: Semantic HTML structure :seedling:
  * [ ] Checkpoint: Basic CSS layout :seedling::seedling:
  * [ ] Checkpoint: Icons are for decoration :blossom:
  * [ ] Checkpoint: Time is floating :hourglass:
  * [ ] Checkpoint: Walk the line :guitar:
  * [ ] Checkpoint: First deployment! :squirrel:
  * [ ] Mission Complete! :checkered_flag:
* **BONUS** -- Skitch the _Responsive Breakpoints_

**Comment by GarrettGraham** [comment]
https://github.com/GarrettGraham/TIY-Assignments/pull/5

**Comment by GarrettGraham** [comment]
https://github.com/GarrettGraham/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Comment by GarrettGraham** [comment]
need to finish the html index and css but instead of columns you may be able to float the time signature and image icon in order to get the same effect as Mary Lou...

**Comment by LoganArnett** [comment]
The layout for the timeline looks great, just need to start tinkering with the monster that is CSS to mess around more with styling. Also, don't forget to ask your peers for the code checks and :+1: 's on the PR.
