### ISSUE TITLE
05 -- Even More Layout -- Evan Klemen

### ISSUE THREAD

**Issue by eklemen** [TheIronYard--Orlando/FEE--2015--SPRING#82]
* [x] L **Yak Shaving** -- The Holy Checklist
    * [x] Open a new _WIP Issue_ with **Tasks**
    * [x] Estimate top-level tasks
    * [x] Update your Cloud 9 workspace: `git pull`
    * [x] Create a new branch from `master`
    * [x] Commit the deletion of your previous assignment
    * [x] Push to Github and open a PR
* [ ] S **Design Specifications** -- Use **Skitch** to create design specs and store them in `specs/`
* [ ] XL [**Vertical Timeline**](http://theironyard-orlando.github.io/FEE--2015--SPRING/)
  * [x] Checkpoint: New project clearinghouse :0:
  S * [ ] Checkpoint: HTML5 Boilerplate :1:
  S * [ ] Checkpoint: Semantic HTML structure :seedling:
  * [x] Checkpoint: Basic CSS layout :seedling::seedling:
  * [x] Checkpoint: Icons are for decoration :blossom:
  * [x] Checkpoint: Time is floating :hourglass:
  * [ ] Checkpoint: Walk the line :guitar:
  * [ ] Checkpoint: First deployment! :squirrel:
  * [ ] Mission Complete! :checkered_flag:
* **BONUS** -- Skitch the _Responsive Breakpoints_

**Comment by eklemen** [comment]
https://github.com/eklemen/TIY-Assignments/pull/6

**Comment by LoganArnett** [comment]
The timelines looking good man, keep fiddling with that CSS to see what works and what doesnt
