### ISSUE TITLE
06 -- More Responsive -- Evan Klemen

### ISSUE THREAD

**Issue by eklemen** [TheIronYard--Orlando/FEE--2015--SPRING#89]
* [x] **Yak Shaving**
  * [x] Create a new _WIP Issue_ named `06 -- More Responsive -- YOUR NAME`with tasks and estimates
  * [x] Ensure your _old_ feature branch is merged and in `master` on Cloud 9
  * [x] Create a new branch on Cloud 9 called `feature/06--more-responsive`
  * [x] Take screenshots of the _medium_ and _small_ breakpoints, add them to Cloud 9, and push them to Github
  * _Immediately_ open a PR!
* [x] **Vertical Timeline -- Medium Size**
  * [x] Checkpoint: Skitched it up!
  * [x] Checkpoint: First medium-size media query!
  * [x] Checkpoint: Well, I applied some styles...
  * [ ] Checkpoint: Nailed it.
* [x] **Vertical Timeline -- Small Size**
  * [x] Checkpoint: Skitched that bad mamma-jamma!
  * [ ] Checkpoint: First small-size media query!
  * [x] Checkpoint: Yo, dawg, I heard you liked CSS...
  * [ ] Checkpoint: Mission complete! :checkered_flag:

* [ ] **Bug checklist**
  * [ ] Smallest size is pushed to the right
  * [ ] Header is hanging off to the left

**Comment by eklemen** [comment]
https://github.com/eklemen/TIY-Assignments/pull/7

**Comment by LoganArnett** [comment]
The timeline looks awesome man, just keep messing with those media queries. Just looking for you to add the link to the `index.html` file and for 1 more :+1: on that PR then you're good for review

**Comment by LoganArnett** [comment]
The newest version looks great still just looking for those two things :arrow_up: and then you're good to go

**Comment by eklemen** [comment]
Link to index.html
https://github.com/eklemen/TIY-Assignments/blob/acd3acc62556bf3390e435c958f25a321a2715cf/pub/index.html
