### ISSUE TITLE
06--More Responsive-- Maddie Fees

### ISSUE THREAD

**Issue by mfees** [TheIronYard--Orlando/FEE--2015--SPRING#91]
* [x] **Yak Shaving** (S)
  * [x] Create a new _WIP Issue_ named `06 -- More Responsive -- YOUR NAME`with tasks and estimates
  * [x] Ensure your _old_ feature branch is merged and in `master` on Cloud 9
  * [x] Create a new branch on Cloud 9 called `feature/06--more-responsive`
  * [x] Take screenshots of the _medium_ and _small_ breakpoints, add them to Cloud 9, and push them to Github
  * [x] Immediately_ open a PR!
* [x] **Vertical Timeline -- Medium Size** (M)
  * [x] Checkpoint: Skitched it up!
  * [x] Checkpoint: First medium-size media query!
  * [x] Checkpoint: Well, I applied some styles...
  * [x] Checkpoint: Nailed it.
* [x] **Vertical Timeline -- Small Size** (XL)
  * [x] Checkpoint: Skitched that bad mamma-jamma!
  * [x] Checkpoint: First small-size media query!
  * [x] Checkpoint: Yo, dawg, I heard you liked CSS...
  * [x] Checkpoint: Mission complete! :checkered_flag:

**Comment by mfees** [comment]
## Deliverables

* A new _WIP Issue_ named `06 -- More Responsive -- YOUR NAME` with tasks and estimates
* A PR from branch `feature/06--more-responsive` into `master` with:
  * a link to your _WIP Issue_ as the description
  * multiple commits no more than 1 hour apart wih _good_ commit messages
  * additional annotated design specs documenting the _small_ and _medium_ breakpoints
  * CSS media queries and style rules added to `pub/css/main.css`
  * feedback from peers and 2x :+1:s
* Comments on your _WIP Issue_ with:
  * a link to your PR
  * a link to your `index.html`
  * a checklist of "Known Issues"

**Comment by mfees** [comment]
https://github.com/mfees/TIY-Assignments/pull/11

**Comment by mfees** [comment]
https://github.com/mfees/TIY-Assignments/blob/feature/06--more-responsive/pub/index.html

**Comment by mfees** [comment]
## I broke this...

* [ ] Thing One

**Comment by jrutishauser** [comment]
:+1: :hand:

**Comment by carolinapowers** [comment]
:+1:

**Comment by eklemen** [comment]
:+1:

**Comment by LoganArnett** [comment]
The timeline looks awesome Maddie, breakpoints are working perfectly. Just make sure to get the 2 :+1: on that PR and then you're good to go
