### ISSUE TITLE
06 -- More-Responsive -- John Alexander

### ISSUE THREAD

**Issue by johnalxndr** [TheIronYard--Orlando/FEE--2015--SPRING#93]
* [x] **Yak Shaving**--S
  * [x] **Create a new _WIP Issue_ named `06 -- More Responsive -- YOUR NAME`with tasks and estimates
  * [x] **Ensure your _old_ feature branch is merged and in `master` on Cloud 9
  * [x] **Create a new branch on Cloud 9 called `feature/06--more-responsive`
  * [x] **Take screenshots of the _medium_ and _small_ breakpoints, add them to Cloud 9, and push them to Github
  * [x] ** _Immediately_ open a PR!
* [x] **Vertical Timeline -- Medium Size**--XL
  * [x] Checkpoint: Skitched it up!--S
  * [x] Checkpoint: First medium-size media query!--M
  * [x] Checkpoint: Well, I applied some styles...--M
  * [x] Checkpoint: Nailed it.-XXXL
* [x] **Vertical Timeline -- Small Size**
  * [x] Checkpoint: Skitched that bad mamma-jamma!--L
  * [x] Checkpoint: First small-size media query!--M
  * [x] Checkpoint: Yo, dawg, I heard you liked CSS...--L
  * [x] Checkpoint: Mission complete! :checkered_flag:--XL

**Comment by johnalxndr** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/93

**Comment by johnalxndr** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/93

**Comment by johnalxndr** [comment]
https://github.com/johnalxndr/TIY-Assignments/blob/feature/06--more-responsive/pub/initializr/index.html

**Comment by LoganArnett** [comment]
The timeline is looking good John, just need to start messing with those media queries. Make sure that you drop a link to your [Open Pull Request](https://github.com/johnalxndr/TIY-Assignments/pull/6) in the comments on this issue and get that last :+1: on the PR and then you're good to go

**Comment by jgarcia99** [comment]
:+1:  yeaaaa

**Comment by LoganArnett** [comment]
The new version looks awesome man. Right now that #93 link is back to this issue, just need to see the link to the PR in these comments and you're good to go

**Comment by johnalxndr** [comment]
@LoganArnett whoopsies https://github.com/johnalxndr/TIY-Assignments/pull/6

**Comment by johnalxndr** [comment]
donzo

**Comment by al-the-x** [comment]
**Pro Tip:** If you want me to review your work, don't close your issue. :wink:
