### ISSUE TITLE
06 -- More Responsive -- Jared Stevick

### ISSUE THREAD

**Issue by jaredstevick** [TheIronYard--Orlando/FEE--2015--SPRING#95]
* [x] M **Yak Shaving**
  * [x] S Create a new _WIP Issue_ named `06 -- More Responsive -- YOUR NAME`with tasks and estimates :new:
  * [x] S Ensure your _old_ feature branch is merged and in `master` on Cloud 9 :cloud: 
  * [x] S Create a new branch on Cloud 9 called `feature/06--more-responsive` :deciduous_tree: 
  * [x] S Take screenshots of the _medium_ and _small_ breakpoints, add them to Cloud 9, and push them to Github :camera: 
  * [x]  Immediately open a PR!
* [x] L **Vertical Timeline -- Medium Size**
  * [x] M Checkpoint: Skitched it up! :art: 
  * [x] M Checkpoint: First medium-size media query! :computer: 
  * [x] M Checkpoint: Well, I applied some styles... :tophat: 
  * [x] M Checkpoint: Nailed it. :hammer: 
* [x] L **Vertical Timeline -- Small Size**
  * [x] M Checkpoint: Skitched that bad mamma-jamma! :art: 
  * [x] M Checkpoint: First small-size media query! :iphone: 
  * [x] M Checkpoint: Yo, dawg, I heard you liked CSS... :dog2: 
  * [x] M Checkpoint: Mission complete! :checkered_flag:

*Version 3.0*
* [x] M **Yak Shaving**
* [x] L Build Site at Small Size
* [x] L **Vertical Timeline -- Medium Size**
  * [x] M Checkpoint: First medium-size media query! :computer: 
  * [x] M Checkpoint: Well, I applied some styles... :tophat: 
  * [x] M Checkpoint: Nailed it. :hammer: 
* [x] L **Vertical Timeline -- Large Size**
  * [x] M Checkpoint: First small-size media query! :iphone: 
  * [x] M Checkpoint: Yo, dawg, I heard you liked CSS... :dog2: 
  * [x] M Checkpoint: Mission complete! :checkered_flag:

**Comment by jaredstevick** [comment]
link to pull request: https://github.com/jaredstevick/TIY-Assignments/pull/11

**Comment by jaredstevick** [comment]
link to index.html: https://github.com/jaredstevick/TIY-Assignments/blob/feature/06--more-responsive/pub/index.html

**Comment by jaredstevick** [comment]
##Known Issues
* [ ] Still need the caret
* [ ] Should make icons smaller at smallest display setting
* [ ] Add a small margin between top of post and bottom of icons
* [ ] Header is boring and could also be made responsive once I put something in there

**Comment by LoganArnett** [comment]
The file that you linked as your index has issues with how its stylesheet relates to it, but I can see your css and media queries there. Look at the file path to see if you can figure it out, it may also help you with that merge conflict. Once you fix that path you're good to go

**Comment by jaredstevick** [comment]
*Known Issues*
* [ ] H3 is centering at larger sizes - needs to stay left
* [ ] Make vertical line shorter
* [ ] Line up icons closer to top of posts
* [ ] Make nav icons larger at full size

**Comment by TaylorFoster90** [comment]
:+1:

**Comment by sak55** [comment]
looking good, you get :cookie: :cookie: :cookie: :cookie: :cookie: :cookie:  and a :+1:

**Comment by jgarcia99** [comment]
:+1:

**Comment by LoganArnett** [comment]
3.0 is looking good man :white_check_mark:
